<a href="https://colab.research.google.com/github/Lingeshkumar24-code/NLP-projects/blob/main/NLP_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
nltk.download('punkt')
nltk.download('stopwords')
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [3]:
data = {
    "Category":[
        "Sports","Sports","Sports","Sports",
        "Politics","Politics","Politics","Politics",
        "Technology","Technology","Technology","Technology",
        "Entertainment","Entertainment","Entertainment","Entertainment",
        "Business","Business","Business","Business"
    ],

    "Article":[

        "India defeated Australia in the cricket world cup match.",
        "Lionel Messi scored two goals in the football tournament.",
        "Virat Kohli played an outstanding innings yesterday.",
        "The Olympic games will begin next month.",

        "The parliament passed a new education bill.",
        "The prime minister addressed the nation.",
        "Election campaigns have started across the country.",
        "The government announced a new tax policy.",

        "Artificial Intelligence is changing healthcare.",
        "Google launched a new AI-powered search feature.",
        "Python is widely used for machine learning.",
        "Cybersecurity threats are increasing every year.",

        "The new movie broke all box office records.",
        "The actor received the best performance award.",
        "Fans celebrated the music concert.",
        "The film trailer gained millions of views.",

        "Stock markets closed at a record high.",
        "The company reported huge quarterly profits.",
        "Investors are buying technology shares.",
        "The startup raised funding from investors."
    ]
}

df = pd.DataFrame(data)

print(df.head())

   Category                                            Article
0    Sports  India defeated Australia in the cricket world ...
1    Sports  Lionel Messi scored two goals in the football ...
2    Sports  Virat Kohli played an outstanding innings yest...
3    Sports           The Olympic games will begin next month.
4  Politics        The parliament passed a new education bill.


In [6]:
stop_words = set(stopwords.words("english"))

def preprocess(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z ]', '', text)

    words = word_tokenize(text)

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df["Clean_Text"] = df["Article"].apply(preprocess)

print(df.head())

   Category                                            Article  \
0    Sports  India defeated Australia in the cricket world ...   
1    Sports  Lionel Messi scored two goals in the football ...   
2    Sports  Virat Kohli played an outstanding innings yest...   
3    Sports           The Olympic games will begin next month.   
4  Politics        The parliament passed a new education bill.   

                                          Clean_Text  
0   india defeated australia cricket world cup match  
1  lionel messi scored two goals football tournament  
2   virat kohli played outstanding innings yesterday  
3                     olympic games begin next month  
4               parliament passed new education bill  


In [7]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["Clean_Text"])

y = df["Category"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

In [9]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [10]:
predictions = model.predict(X_test)

In [11]:
print("Accuracy:", accuracy_score(y_test, predictions))

print("\nClassification Report")

print(classification_report(y_test, predictions))

Accuracy: 0.0

Classification Report
               precision    recall  f1-score   support

     Business       0.00      0.00      0.00       1.0
Entertainment       0.00      0.00      0.00       1.0
     Politics       0.00      0.00      0.00       0.0
       Sports       0.00      0.00      0.00       2.0
   Technology       0.00      0.00      0.00       1.0

     accuracy                           0.00       5.0
    macro avg       0.00      0.00      0.00       5.0
 weighted avg       0.00      0.00      0.00       5.0



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

In [12]:
print(confusion_matrix(y_test, predictions))

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [0 0 1 0 0]]


In [13]:
news = [
    "Apple launched a new AI powered smartphone with advanced processor."
]

news_clean = [preprocess(x) for x in news]

news_vector = vectorizer.transform(news_clean)

prediction = model.predict(news_vector)

print("Category:", prediction[0])

Category: Politics


In [16]:
news = [
    "The finance minister announced the annual budget."
]

news_clean = [preprocess(x) for x in news]

news_vector = vectorizer.transform(news_clean)

prediction = model.predict(news_vector)

print("Category:", prediction[0])

Category: Politics
